services:
  - type: web
    name: lung-cancer-prediction-api
    env: python
    buildCommand: python -m pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: CORS_ORIGINS
        value: "*" # Update this to your Vercel URL after deployment
